# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMrFihWcvZJI96uCf_quiuOS77NpPdcM
"""

!apt-get -qq install openjdk-11-jdk-headless > /dev/null
!pip -q install pyspark

from pyspark.sql import SparkSession

spark = (SparkSession.builder
         .appName("Lab Spark SQL - FIFA")
         .getOrCreate())

spark

from pyspark.sql import functions as F

path = "/content/fifaworldcup.csv"   # change si ton fichier a un autre nom

df = (spark.read
      .option("header", True)
      .option("inferSchema", True)
      .csv(path))

df.printSchema()
df.show(5, truncate=False)

df.createOrReplaceTempView("matches")

df2 = (df
  .withColumn("date", F.to_date("date"))
  .withColumn("home_score", F.col("home_score").cast("int"))
  .withColumn("away_score", F.col("away_score").cast("int"))
  .withColumn("neutral", F.col("neutral").cast("boolean"))
)

df2.createOrReplaceTempView("matches")
df2.printSchema()

spark.sql("""SELECT COUNT(*) AS nb_matchs FROM matches""").show()

spark.sql("""
SELECT YEAR(MIN(date)) AS annee_min, YEAR(MAX(date)) AS annee_max
FROM matches
""").show()

spark.sql("""
SELECT tournament, COUNT(*) AS nb
FROM matches
GROUP BY tournament
ORDER BY nb DESC
LIMIT 10
""").show(truncate=False)

spark.sql("""
SELECT COUNT(*) AS nb_neutral
FROM matches
WHERE neutral = true
""").show()

spark.sql("""
SELECT country, COUNT(*) AS nb
FROM matches
GROUP BY country
ORDER BY nb DESC
LIMIT 10
""").show(truncate=False)

from pyspark.sql import functions as F

df_clean = (df
  .withColumn("home_score",
              F.when(F.col("home_score") == "NA", None)
               .otherwise(F.col("home_score")).cast("int"))
  .withColumn("away_score",
              F.when(F.col("away_score") == "NA", None)
               .otherwise(F.col("away_score")).cast("int"))
)

df_clean.createOrReplaceTempView("matches")
df_clean.printSchema()

spark.sql("""
SELECT COUNT(*) AS nb_nuls
FROM matches
WHERE home_score = away_score
""").show()

spark.sql("""
SELECT date, home_team, away_team, home_score, away_score,
       (home_score + away_score) AS total
FROM matches
WHERE (home_score + away_score) > 6
ORDER BY total DESC
""").show(truncate=False)

spark.sql("""
WITH home AS (
  SELECT home_team AS team, COUNT(*) AS n FROM matches GROUP BY home_team
),
away AS (
  SELECT away_team AS team, COUNT(*) AS n FROM matches GROUP BY away_team
)
SELECT team, SUM(n) AS total_matches
FROM (
  SELECT * FROM home
  UNION ALL
  SELECT * FROM away
)
GROUP BY team
ORDER BY total_matches DESC
""").show(truncate=False)

spark.sql("""
WITH h AS (
  SELECT home_team AS team, SUM(home_score) AS goals FROM matches GROUP BY home_team
),
a AS (
  SELECT away_team AS team, SUM(away_score) AS goals FROM matches GROUP BY away_team
)
SELECT team, SUM(goals) AS total_goals
FROM (
  SELECT * FROM h
  UNION ALL
  SELECT * FROM a
)
GROUP BY team
ORDER BY total_goals DESC
LIMIT 10
""").show(truncate=False)

spark.sql("""
SELECT (FLOOR(YEAR(date)/10)*10) AS decade,
       AVG(home_score + away_score) AS avg_goals
FROM matches
GROUP BY (FLOOR(YEAR(date)/10)*10)
ORDER BY decade
""").show()

spark.sql("""
SELECT tournament, YEAR(date) AS year, COUNT(*) AS nb
FROM matches
GROUP BY tournament, YEAR(date)
ORDER BY tournament, year
""").show(truncate=False)

spark.sql("""
SELECT home_team AS team,
       SUM(CASE WHEN home_score > away_score THEN 1 ELSE 0 END) AS home_wins
FROM matches
GROUP BY home_team
ORDER BY home_wins DESC
""").show(truncate=False)

spark.sql("""
WITH all_games AS (
  SELECT home_team AS team,
         CASE WHEN home_score > away_score THEN 'W'
              WHEN home_score < away_score THEN 'L'
              ELSE 'D' END AS res
  FROM matches
  UNION ALL
  SELECT away_team AS team,
         CASE WHEN away_score > home_score THEN 'W'
              WHEN away_score < home_score THEN 'L'
              ELSE 'D' END AS res
  FROM matches
)
SELECT team,
       SUM(CASE WHEN res='W' THEN 1 ELSE 0 END) AS wins,
       SUM(CASE WHEN res='L' THEN 1 ELSE 0 END) AS losses,
       SUM(CASE WHEN res='D' THEN 1 ELSE 0 END) AS draws
FROM all_games
GROUP BY team
ORDER BY wins DESC
""").show(truncate=False)

spark.sql("""
SELECT neutral,
       AVG(home_score + away_score) AS avg_total_goals
FROM matches
GROUP BY neutral
""").show()

spark.sql("""
SELECT date, home_team, away_team, home_score, away_score,
       ABS(home_score - away_score) AS diff
FROM matches
ORDER BY diff DESC
LIMIT 5
""").show(truncate=False)

spark.sql("""
WITH stats AS (
  SELECT home_team AS team,
         SUM(home_score) AS scored,
         SUM(away_score) AS conceded
  FROM matches GROUP BY home_team
  UNION ALL
  SELECT away_team AS team,
         SUM(away_score) AS scored,
         SUM(home_score) AS conceded
  FROM matches GROUP BY away_team
)
SELECT team,
       SUM(scored) AS goals_scored,
       SUM(conceded) AS goals_conceded,
       (SUM(scored) - SUM(conceded)) AS goal_average
FROM stats
GROUP BY team
ORDER BY goal_average DESC
""").show(truncate=False)

spark.sql("""
WITH wins_year AS (
  SELECT YEAR(date) AS year, home_team AS team,
         SUM(CASE WHEN home_score > away_score THEN 1 ELSE 0 END) AS wins
  FROM matches
  GROUP BY YEAR(date), home_team
  UNION ALL
  SELECT YEAR(date) AS year, away_team AS team,
         SUM(CASE WHEN away_score > home_score THEN 1 ELSE 0 END) AS wins
  FROM matches
  GROUP BY YEAR(date), away_team
),
agg AS (
  SELECT year, team, SUM(wins) AS wins
  FROM wins_year
  GROUP BY year, team
)
SELECT year, team, wins,
       ROW_NUMBER() OVER (PARTITION BY year ORDER BY wins DESC) AS rk
FROM agg
ORDER BY year, rk
""").show(truncate=False)

spark.sql("""
SELECT (FLOOR(YEAR(date)/10)*10) AS decade, COUNT(*) AS nb
FROM matches
GROUP BY (FLOOR(YEAR(date)/10)*10)
ORDER BY decade
""").show()

year_target = 2010

spark.sql(f"""
WITH all_games AS (
  SELECT YEAR(date) AS year, home_team AS team,
         CASE WHEN home_score < away_score THEN 1 ELSE 0 END AS lost
  FROM matches
  UNION ALL
  SELECT YEAR(date) AS year, away_team AS team,
         CASE WHEN away_score < home_score THEN 1 ELSE 0 END AS lost
  FROM matches
)
SELECT team
FROM all_games
WHERE year = {year_target}
GROUP BY team
HAVING SUM(lost) = 0
ORDER BY team
""").show(truncate=False)

spark.sql("""
WITH games AS (
  SELECT date, home_team AS team,
         CASE WHEN home_score > away_score THEN 1 ELSE 0 END AS win
  FROM matches
  UNION ALL
  SELECT date, away_team AS team,
         CASE WHEN away_score > home_score THEN 1 ELSE 0 END AS win
  FROM matches
),
ord AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY team ORDER BY date) AS rn,
    ROW_NUMBER() OVER (PARTITION BY team, win ORDER BY date) AS rn2
  FROM games
),
streaks AS (
  SELECT team, win, (rn - rn2) AS grp, COUNT(*) AS len
  FROM ord
  WHERE win = 1
  GROUP BY team, win, (rn - rn2)
)
SELECT team, MAX(len) AS longest_win_streak
FROM streaks
GROUP BY team
ORDER BY longest_win_streak DESC
""").show(truncate=False)

spark.sql("""
WITH wins_tour AS (
  SELECT tournament, home_team AS team,
         SUM(CASE WHEN home_score > away_score THEN 1 ELSE 0 END) AS wins
  FROM matches
  GROUP BY tournament, home_team
  UNION ALL
  SELECT tournament, away_team AS team,
         SUM(CASE WHEN away_score > home_score THEN 1 ELSE 0 END) AS wins
  FROM matches
  GROUP BY tournament, away_team
),
agg AS (
  SELECT tournament, team, SUM(wins) AS wins
  FROM wins_tour
  GROUP BY tournament, team
),
ranked AS (
  SELECT tournament, team, wins,
         ROW_NUMBER() OVER (PARTITION BY tournament ORDER BY wins DESC) AS rk
  FROM agg
)
SELECT tournament, team, wins
FROM ranked
WHERE rk = 1
ORDER BY tournament
""").show(truncate=False)

spark.sql("""
WITH home AS (
  SELECT home_team AS team,
         SUM(CASE WHEN home_score > away_score THEN 1 ELSE 0 END) AS home_wins,
         COUNT(*) AS home_games
  FROM matches
  GROUP BY home_team
),
away AS (
  SELECT away_team AS team,
         SUM(CASE WHEN away_score > home_score THEN 1 ELSE 0 END) AS away_wins,
         COUNT(*) AS away_games
  FROM matches
  GROUP BY away_team
)
SELECT COALESCE(h.team, a.team) AS team,
       COALESCE(home_games, 0) AS home_games,
       COALESCE(home_wins, 0) AS home_wins,
       COALESCE(away_games, 0) AS away_games,
       COALESCE(away_wins, 0) AS away_wins
FROM home h
FULL OUTER JOIN away a ON h.team = a.team
ORDER BY (COALESCE(home_wins,0) + COALESCE(away_wins,0)) DESC
""").show(truncate=False)