# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TapWRsCsFRQmcWAYt4JOMwPNhNypkZfp
"""

!pip -q install pymongo

from pymongo import MongoClient
uri = "mongodb+srv://souhailaomri3_db_user:supmti2025@cluster0.h2rfzl2.mongodb.net/BankDB?retryWrites=true&w=majority"
client = MongoClient(uri)
# Accéder à la base de données
db = client["BankDB"]
transactions_collection = db["transactions"]
# Vérification de la connexion
print("Connexion à MongoDB Atlas réussie!")

#creer un pipeline d’ Aggregation pour calculer le montant total transaction par type
pipeline = [
{"$group": {"_id": "$Transaction Type", "totalAmount": {"$sum": "$TransactionAmount"}}}]
# executer la requete d’agrégation
result = transactions_collection.aggregate(pipeline)
# afficher les resultats
for doc in result:print(f"Transaction Type: {doc['_id']}, Total Amount: {doc['totalAmount']}")

pipeline = [
    {
        "$group": {
            "_id": "$Transaction Status",
            "total": {"$sum": 1}
        }
    }
]

for doc in transactions_collection.aggregate(pipeline):
    print(doc)

pipeline = [
    {
        "$group": {
            "_id": "$Transaction Type",
            "avgAmount": {"$avg": "$Transaction Amount"}
        }
    }
]

for doc in transactions_collection.aggregate(pipeline):
    print(doc)

pipeline = [
    {
        "$group": {
            "_id": "$Transaction Type",
            "avgAmount": {"$avg": "$Transaction Amount"}
        }
    }
]

for doc in transactions_collection.aggregate(pipeline):
    print(doc)

pipeline = [
    {
        "$group": {
            "_id": "$Sender Account ID",
            "totalSent": {"$sum": "$Transaction Amount"}
        }
    },
    {"$sort": {"totalSent": -1}},
    {"$limit": 5}
]

for doc in transactions_collection.aggregate(pipeline):
    print(doc)

total_transactions = transactions_collection.count_documents({})
print("Nombre total de transactions :", total_transactions)

pipeline = [
    {
        "$group": {
            "_id": None,
            "totalAmount": {"$sum": "$Transaction Amount"}
        }
    }
]

print(list(transactions_collection.aggregate(pipeline))[0])

pipeline = [
    {
        "$group": {
            "_id": None,
            "total": {"$sum": 1},
            "failed": {
                "$sum": {
                    "$cond": [
                        {"$eq": ["$Transaction Status", "Failed"]},
                        1,
                        0
                    ]
                }
            }
        }
    },
    {
        "$project": {
            "_id": 0,
            "total": 1,
            "failed": 1,
            "failureRatePercent": {
                "$multiply": [
                    {"$divide": ["$failed", "$total"]},
                    100
                ]
            }
        }
    }
]

print(list(transactions_collection.aggregate(pipeline))[0])

fraud_count = transactions_collection.count_documents({"Fraud Flag": "True"})
print("Nombre de transactions frauduleuses :", fraud_count)