# -*- coding: utf-8 -*-
"""TP  Spark Streaming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrUpuAylHuH8Ar2H3KA0yUCz-0vD-uVi
"""

!pip -q install pyspark

# =========================
# SECTION 2 : Socket Server
# =========================
import socket, time, threading

def start_socket_server():
    # Serveur local : envoie des messages en continu
    host = "localhost"
    port = 9999

    s = socket.socket()
    s.bind((host, port))
    s.listen(1)

    conn, addr = s.accept()
    print("Client connecté :", addr)

    messages = [
        "spark streaming dstream",
        "spark spark streaming",
        "big data spark"
    ]

    # Envoi en boucle (toutes les 2 sec)
    while True:
        for msg in messages:
            conn.send((msg + "\n").encode())
            time.sleep(2)

# On lance le serveur dans un thread (pour ne pas bloquer le notebook)
threading.Thread(target=start_socket_server, daemon=True).start()

# ==========================================
# SECTION 3 : SparkContext + StreamingContext
# ==========================================
from pyspark import SparkContext
from pyspark.streaming import StreamingContext

sc = SparkContext.getOrCreate()

# batch interval = 5 secondes
ssc = StreamingContext(sc, 5)

# ==========================
# SECTION 4 : Lecture DStream
# ==========================
lines = ssc.socketTextStream("localhost", 9999)

# ==========================
# SECTION 5 : WordCount
# ==========================
words = lines.flatMap(lambda line: line.split(" "))
pairs = words.map(lambda w: (w, 1))
counts = pairs.reduceByKey(lambda a, b: a + b)

# ==========================
# SECTION 6 : Affichage + Start
# ==========================
counts.pprint()                 # affiche chaque batch
ssc.start()                     # démarre le streaming
ssc.awaitTerminationOrTimeout(30)  # exécute 30 secondes
ssc.stop(stopSparkContext=False)   # stop streaming (garde SparkContext)

"""with open("/content/messages.txt", "w", encoding="utf-8") as f:
    f.write("spark streaming dstream\n")
    f.write("spark spark streaming\n")
    f.write("big data spark\n")
    f.write("hello spark\n")
    f.write("streaming big data\n")

print("✅ messages.txt créé !")

"""

import socket, time, threading, random

def start_socket_server_from_file():
    host = "localhost"
    port = 9999

    s = socket.socket()
    s.bind((host, port))
    s.listen(1)

    print("✅ Serveur prêt. Attente connexion Spark...")
    conn, addr = s.accept()
    print("✅ Client connecté :", addr)

    with open("/content/messages.txt", "r", encoding="utf-8") as f:
        lines_file = [line.strip() for line in f if line.strip()]

    while True:
        msg = random.choice(lines_file)
        conn.send((msg + "\n").encode())
        time.sleep(2)

threading.Thread(target=start_socket_server_from_file, daemon=True).start()

from pyspark import SparkContext
from pyspark.streaming import StreamingContext

sc = SparkContext.getOrCreate()
ssc = StreamingContext(sc, 5)

lines = ssc.socketTextStream("localhost", 9999)

words = lines.flatMap(lambda line: line.split(" "))
pairs = words.map(lambda w: (w, 1))
counts = pairs.reduceByKey(lambda a, b: a + b)

counts.pprint()

ssc.start()
ssc.awaitTerminationOrTimeout(30)
ssc.stop(stopSparkContext=False)